'use strict';
const $=id=>document.getElementById(id);
const shots=[
 {id:'zoom-bottom-right',kind:'camera',name:'右下角缓慢放大',icon:'↘',en:'FOCUS / ZOOM IN',duration:2.167,ease:'power2.inOut',description:'把画面逐渐放大，同时将视线移向右下角。适合从整体画面推进到一个细节。',path:'整体 → 右下角细节',curve:'M0 43C90 43 130 5 240 5'},
 {id:'zoom-out',kind:'camera',name:'缩小展开',icon:'⊖',en:'REVEAL / ZOOM OUT',duration:1.67,ease:'power3.out',description:'从近景退回全景，前段变化较快，接近终点时放慢，让更多内容自然进入视野。',path:'近景 → 完整画面',curve:'M0 43C30 5 95 5 240 5'},
 {id:'drift-up',kind:'camera',name:'缓慢向上',icon:'↑',en:'DRIFT / MOVE UP',duration:2,ease:'sine.out',description:'内容缓慢向上移动，轻柔停住。适合标题、画面段落和需要留出阅读时间的镜头。',path:'低位 → 上移 → 停留',curve:'M0 43C100 14 160 5 240 5'},
 {id:'left-bounce',kind:'type',name:'左弹打字',icon:'←',en:'TYPE / LEFT BOUNCE',title:'灵感向左',subtitle:'让每个字都有自己的节奏',description:'标题从右向左进入遮罩，轻微回弹后落位。副标题跟随红色光标逐字出现。',path:'分词左移 → 回弹 → 打字',curve:'M0 43C40 43 55 0 95 4S130 7 155 5H240'},
 {id:'right-bounce',kind:'type',name:'向右弹打字',icon:'→',en:'TYPE / RIGHT BOUNCE',title:'Make it move',subtitle:'Small movements. Clear ideas.',description:'标题分词从下方进入，同时向右落位。后一个词错峰出现，接上逐字输入的节奏。',path:'分词弹入 → 向右落位 → 打字',curve:'M0 43C40 43 55 0 95 4S130 7 155 5H240'},
 {id:'blur-up',kind:'type',name:'模糊向上打字',icon:'⇡',en:'TYPE / BLUR REVEAL',title:'慢慢清晰',subtitle:'从模糊想法，到清晰表达。',description:'文字上移时逐渐变清晰，透明度与模糊程度同步变化，最后由光标补上副标题。',path:'模糊上移 → 聚焦 → 打字',curve:'M0 43C30 5 95 5 240 5'}
];
let selected=shots[0],instance=null,loop=true,loopDelay=null,playing=false,mediaURL=null,mediaType=null,mediaName='',ratio='wide',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function makeDemo(id){const root=document.createElement('div');root.className='demo-scene';if(id==='zoom-bottom-right')root.innerHTML='<div class="diagram-ticks"></div><div class="ring-label"><small>A SMALL PART OF SOMETHING</small><h3>BIG IDEAS</h3></div><div class="demo-ring"></div><div class="mini-block"><strong>THE DETAIL</strong><div class="mini-ring"></div></div>';else if(id==='zoom-out')root.innerHTML='<div class="diagram-ticks"></div><div class="scene-top">SEE THE BIGGER PICTURE</div><div class="demo-card-grid"><div class="demo-card"><span>01</span><strong>THINK</strong></div><div class="demo-card"><span>02</span><strong>CREATE</strong></div><div class="demo-card"><span>03</span><strong>SHARE</strong></div></div><div class="zoom-caption">EVERY PIECE CONNECTS.</div>';else root.innerHTML='<div class="diagram-ticks"></div><div class="rise-title"><h3>KEEP GROWING.</h3><p>Small steps. Real progress.</p></div><div class="demo-bars"><span></span><span></span><span></span></div>';return root;}
function renderList(filter='all'){const list=$('shot-list');list.textContent='';shots.filter(s=>filter==='all'||s.kind===filter).forEach(s=>{const b=document.createElement('button');b.className='shot-button'+(s.id===selected.id?' active':'');b.dataset.shot=s.id;b.setAttribute('aria-pressed',String(s.id===selected.id));b.innerHTML=`<span class="shot-icon" aria-hidden="true">${s.icon}</span><span><strong>${s.name}</strong><small>${s.en}</small></span>`;b.onclick=()=>select(s.id);list.append(b);});}
function cameraOptions(){return {preset:selected.id,duration:Number($('duration').value),intensity:Number($('intensity').value),ease:$('ease').value,fit:'cover'};}
function typeOptions(){const width=$('stage').clientWidth;return {preset:selected.id,title:$('title').value,subtitle:$('subtitle').value,fontSize:Math.min(76,Math.max(22,(width-48)/8)),speed:Number($('type-speed').value),color:$('text-color').value,accent:'#e62919'};}
function updateView(){const t=instance.timeline.time();$('timeline').max=instance.duration;$('timeline').value=t;$('time').textContent=`${t.toFixed(2)} / ${instance.duration.toFixed(2)} s`;}
function stopLoop(){loopDelay?.kill();loopDelay=null;}
function setState(value){playing=value;$('play').textContent=value?'Ⅱ':'▶';$('play').setAttribute('aria-label',value?'暂停':'播放');$('play-state').textContent=value?'预览中':'已暂停';}
function mediaSync(t,play=false){const media=instance?.media;if(media instanceof HTMLVideoElement){if(Number.isFinite(media.duration))media.currentTime=Math.min(t,Math.max(0,media.duration-.01));if(play)media.play().catch(()=>{});else media.pause();}}
function start(){stopLoop();if(instance.timeline.time()>=instance.duration-.001){instance.timeline.seek(0);mediaSync(0);}setState(true);instance.timeline.play();instance.media?.play?.().catch(()=>{});}
function pause(){stopLoop();setState(false);instance.timeline.pause();instance.media?.pause?.();}
function rebuild(autoplay=true){stopLoop();instance?.media?.pause?.();instance?.destroy();$('stage').textContent='';$('stage').className=selected.kind==='type'?'type-stage':ratio;const options=selected.kind==='camera'?cameraOptions():typeOptions();if(selected.kind==='camera'){if(mediaURL){options.src=mediaURL;options.mediaType=mediaType;options.alt=mediaName;}else options.content=makeDemo(selected.id);instance=CameraMotion.mount($('stage'),options);}else instance=TypeMotion.mount($('stage'),options);
 if(instance.media instanceof HTMLVideoElement)instance.media.muted=true;
 instance.timeline.eventCallback('onUpdate',updateView);instance.timeline.eventCallback('onComplete',()=>{instance.media?.pause?.();if(loop&&playing)loopDelay=gsap.delayedCall(.65,()=>{instance.timeline.seek(0);mediaSync(0,true);instance.timeline.play();});else setState(false);});
 $('duration-value').textContent=Number($('duration').value).toFixed(1)+' s';$('intensity-value').textContent=Math.round(Number($('intensity').value)*100)+'%';updateView();setState(false);if(autoplay&&!reduced)start();else if(reduced){instance.timeline.seek(instance.duration);updateView();}updateCode();}
function select(id){selected=shots.find(s=>s.id===id)||shots[0];$('shot-name').textContent=selected.name;$('shot-code').textContent=selected.en;$('kind-label').textContent=selected.kind==='camera'?'镜头运动':'文字动效';$('description').textContent=selected.description;$('motion-path').textContent=selected.path;$('curve-path').setAttribute('d',selected.curve);$('camera-controls').hidden=selected.kind!=='camera';$('type-controls').hidden=selected.kind!=='type';if(selected.kind==='camera'){$('duration').value=selected.duration;$('ease').value=selected.ease;$('intensity').value=1;}else{$('title').value=selected.title;$('subtitle').value=selected.subtitle;$('type-speed').value='1';$('text-color').value='#171717';}history.replaceState(null,'','#'+selected.id);renderList(document.querySelector('[data-filter].active').dataset.filter);rebuild();}
function updateCode(){let text;if(selected.kind==='camera'){const options=cameraOptions();text=`<link rel="stylesheet" href="lib/camera-motion.css">\n<div id="shot" style="height:360px;overflow:hidden"></div>\n<template id="content">\n  <div style="width:100%;height:100%;background:#152010;\n    color:#d5eeb7;display:grid;place-items:center;\n    font:700 48px system-ui">YOUR STORY</div>\n</template>\n<script src="vendor/gsap.min.js"><\/script>\n<script src="lib/camera-motion.js"><\/script>\n<script>\nconst shot = CameraMotion.mount(document.querySelector('#shot'), {\n  ...${JSON.stringify(options,null,2).replace(/\n/g,'\n  ')},\n  content: document.querySelector('#content').content.firstElementChild\n  // 图片/视频：用 src: './your-image.jpg' 替换 content\n  // 视频同时设置 mediaType: 'video'\n});\nshot.timeline.play();\n// shot.timeline.pause() / restart() / seek(1)\n// shot.destroy(); // 卸载时清理\n<\/script>`;}else{const options=typeOptions();options.fontSize=64;text=`<link rel="stylesheet" href="lib/type-motion.css">\n<div id="title"></div>\n<script src="vendor/gsap.min.js"><\/script>\n<script src="lib/type-motion.js"><\/script>\n<script>\nconst shot = TypeMotion.mount(document.querySelector('#title'),\n  ${JSON.stringify(options,null,2).replace(/\n/g,'\n  ')}\n);\nshot.timeline.play();\n// shot.timeline.pause() / restart() / seek(1)\n// shot.destroy();\n<\/script>`;}$('code').textContent=text;$('copy-status').textContent='无需联网，无需构建。';}
$('play').onclick=()=>playing?pause():start();$('restart').onclick=()=>{pause();instance.timeline.seek(0);mediaSync(0);start();};$('loop').onclick=()=>{loop=!loop;$('loop').setAttribute('aria-pressed',String(loop));if(!loop){stopLoop();if(instance.timeline.time()>=instance.duration-.001)setState(false);}};$('timeline').oninput=()=>{pause();const t=Number($('timeline').value);instance.timeline.seek(t);mediaSync(t);updateView();};
['duration','intensity'].forEach(id=>$(id).oninput=()=>rebuild());$('ease').onchange=()=>rebuild();['title','subtitle','text-color'].forEach(id=>$(id).oninput=()=>rebuild());$('type-speed').onchange=()=>rebuild();$('reset').onclick=()=>select(selected.id);
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('active',el===b));renderList(b.dataset.filter);});document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{ratio=b.dataset.ratio;document.querySelectorAll('[data-ratio]').forEach(el=>el.classList.toggle('active',el===b));$('ratio-label').textContent={wide:'16 : 10',portrait:'9 : 16',square:'1 : 1'}[ratio];rebuild();});
$('upload').onchange=()=>{const file=$('upload').files[0];if(!file)return;if(!/^image\/|^video\//.test(file.type)){$('material-name').textContent='请选择图片或视频文件';return;}pause();instance?.destroy();if(mediaURL)URL.revokeObjectURL(mediaURL);mediaURL=URL.createObjectURL(file);mediaType=file.type.startsWith('video/')?'video':'image';mediaName=file.name;$('material-name').textContent=file.name;$('clear-media').hidden=false;rebuild();if(instance.media){instance.media.addEventListener('error',()=>{$('material-name').textContent='此格式无法预览，请换一张图片或 MP4 视频';pause();},{once:true});}};
$('clear-media').onclick=()=>{pause();instance?.destroy();if(mediaURL)URL.revokeObjectURL(mediaURL);mediaURL=null;mediaType=null;mediaName='';$('upload').value='';$('material-name').textContent='当前：内置演示场景';$('clear-media').hidden=true;rebuild();};
$('show-code').onclick=()=>{updateCode();$('code-dialog').showModal();};$('close-code').onclick=()=>$('code-dialog').close();$('code-dialog').onclick=e=>{if(e.target===$('code-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('code').textContent);$('copy-status').textContent='已复制，可以粘贴到项目中';}catch{$('copy-status').textContent='请选中上方代码手动复制';}};
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>rebuild(false),150);});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('beforeunload',()=>{instance?.destroy();if(mediaURL)URL.revokeObjectURL(mediaURL);});
select(shots.some(s=>s.id===location.hash.slice(1))?location.hash.slice(1):'zoom-bottom-right');
